config/routes.rb
Rails.application.routes.draw do
  get "/success", to: "site#success"
  root to: "games#new"
  resources :players do
    resources :games do
      resources :questions
      member do
        get 'intro'
        get 'mercy_success'
        get 'mercy_failure'
        get 'punishment_success'
        get 'punishment_failure'
        get 'turra'
        get 'cruz'
        get 'felices'
      end
    end
  end
  resources :sentences
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player
  has_many :questions
  has_many :sentences, through: :questions
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :games
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :game
  belongs_to :sentence
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @player = Player.new
  end

  def create
    player = Player.where(nickname: "Player").first_or_create(nickname: "Player")
    game = Game.create(player: player)
    game.questions.destroy_all
    redirect_to "/players/1/games/#{game.id}/intro"
  end

  def show
    @player = Player.find(params[:player_id])
    @game = @player.games.find(params[:id])
  end

  def intro
    @player = Player.find(params[:player_id])
    @game = @player.games.find(params[:id])
  end

  def mercy_success
    @player = Player.find(params[:player_id])
    @game = @player.games.find(params[:id])
  end

  def mercy_failure
    @player = Player.find(params[:player_id])
    @game = @player.games.find(params[:id])
  end

  def punishment_success
    @player = Player.find(params[:player_id])
    @game = @player.games.find(params[:id])
  end

  def punishment_failure
    @player = Player.find(params[:player_id])
    @game = @player.games.find(params[:id])
  end

  def success
    @player = Player.find(params[:player_id])
    @game = @player.games.find(params[:id])
  end

  def failure
    @player = Player.find(params[:player_id])
    @game = @player.games.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def create
    player = Player.where(nickname: "Player").first_or_create(nickname: "Player")
    game = player.games.create
    redirect_to player_game_path(player, game)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    player = Player.find(params[:player_id])
    game = Game.find(params[:game_id])
    question = QuestionDispatcher.new(game).next

    render json: question.id == nil ? nil : question.sentence
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def welcome
    @game = Game.new
  end

  def success
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/games/cruz.html.slim
="Cruz"

app/views/games/intro.html.slim
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.min.js"
// div
// 	="stnaheusatehousntaoh"

css:
  body {
    margin: 0;
  }
javascript:
    var audio = new Audio('/07_joy_to_the_world.mp3');
    audio.play();

  var game = new Phaser.Game("100", "100", Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

  function preload() {
    game.load.spritesheet('nextButton', '/siguiente.sprite_sheet.png', 200, 70);
  }

  var mummy;
  var anim;
  var loopText;
  var punish;
  var mercy;
  var text;
  var letter;
  var content = [
    'Querido Santa',
    '',
    'Este año me he portado muy bien',
    'y he aprobado todo, incluso las mates.',
    'Me gustaria que me trajeses una bici,',
    'y tambien una consola, pero sobre todo,',
    'quiero que me libres de los cuñados,',
    'por favor Santa !! ',
    'no quiero que me den mas la turra !!',
    '',
    'Atentamente',
    'Justice boy'
  ];
  var style;
  var currentQuestion;

    var line = [];

    var wordIndex = 0;
    var lineIndex = 0;

    var wordDelay = 120;
    var lineDelay = 400;

  function create() {



  	game.stage.backgroundColor = "#e4a724";

    // mummy = game.add.sprite(20, 100, 'mummy', 5);
    // mummy.scale.set(4);
    // mummy.smoothed = false;
    // anim = mummy.animations.add('walk');

    // anim.play(10, true);

    // style = { font: "bold 24px fedra", fill: "red", wordWrap: true, wordWrapWidth: 350 , align: "left"};
    // text = game.add.text(0, 0, "snateuhosa aoenuh", style);
    letter = game.add.text(32, 80, '', { font: "36px fedra", fill: "#352114" });

    nextLine();
  }

  function nextAction(){
    window.location.href = "#{ player_game_path(@player, @game)}";
  }

  function update() {

  }


    function nextLine() {

        if (lineIndex === content.length)
        {
            next = game.add.button(40, 650, 'nextButton', nextAction, this, 0, 1);
            return;
        }

        //  Split the current line on spaces, so one word per array element
        line = content[lineIndex].split(' ');

        //  Reset the word index to zero (the first word in the line)
        wordIndex = 0;

        //  Call the 'nextWord' function once for each word in the line (line.length)
        game.time.events.repeat(wordDelay, line.length, nextWord, this);

        //  Advance to the next line
        lineIndex++;

    }

    function nextWord() {

        //  Add the next word onto the text string, followed by a space
        letter.text = letter.text.concat(line[wordIndex] + " ");

        //  Advance the word index to the next word in the line
        wordIndex++;

        //  Last word?
        if (wordIndex === line.length)
        {
            //  Add a carriage return
            letter.text = letter.text.concat("\n");

            //  Get the next line after the lineDelay amount of ms has elapsed
            game.time.events.add(lineDelay, nextLine, this);
        }

    }   

app/views/games/mercy_failure.html.slim
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.min.js"
css:
  body {
    margin: 0;
  }
javascript:

  var text;
  var game = new Phaser.Game("100", "100", Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

  function preload() {
    game.load.spritesheet('risa', '/risa.png', 1040, 740, 2);
    game.load.spritesheet('button', '/button_sprite_sheet.png', 193, 71);
  }

  var mummy;
  var anim;
  var loopText;
  var punish;
  var mercy;
  // var text;
  var style;
  var currentQuestion;

  function create() {
    risa = game.add.sprite(0, 0, 'risa', 18);
    risa.scale.set(1);
    risa.smoothed = false;
    anim = risa.animations.add('walk');
    anim.onLoop.add(animationLooped, this);
    // text = game.add.text(30, 350, 'Fallaste burlancaster', style);

    anim.play(5, true);
  }

  function animationLooped(sprite, animation) {
    if (animation.loopCount === 10)
    {
      style = { font: "bold 24px fedra", fill: "#fff", wordWrap: true, wordWrapWidth: 490 , align: "center"};
      nextAction();
    }
  }

  function nextAction() {
    window.location.href = "#{ turra_player_game_path(@player, @game)}";
  }


  function update() {

  }

app/views/games/mercy_success.html.slim
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.min.js"
css:
  body {
    margin: 0;
  }
javascript:

  var text;
  var game = new Phaser.Game("100", "100", Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

  function preload() {
    game.load.spritesheet('fruits', '/fruitnveg64wh37.png', 64, 37, 37);
    game.load.spritesheet('button', '/button_sprite_sheet.png', 193, 71);
  }

  var mummy;
  var anim;
  var loopText;
  var punish;
  var mercy;
  var text;
  var style;
  var currentQuestion;

  function create() {
    fruits = game.add.sprite(20, 100, 'fruits', 2);
    fruits.scale.set(4);
    fruits.smoothed = false;
    anim = fruits.animations.add('walk');
    anim.onLoop.add(animationLooped, this);

    anim.play(10, true);
  }

  function animationLooped(sprite, animation) {
    if (animation.loopCount === 1)
    {
      style = { font: "bold 24px fedra", fill: "#fff", wordWrap: true, wordWrapWidth: 490 , align: "center"};
      text = game.add.text(30, 350, 'Éxitooo' , style);
      game.add.button(200, 650, 'button', nextAction, this, 2, 1, 0);

    }
  }

  function nextAction() {
    window.location.href = "#{ player_game_path(@player, @game)}";
  }


  function update() {

  }

app/views/games/new.html.slim
=link_to("", "/players/1/games", id: "link", method: :post)

scss:
  body {
    margin: 0;
    background: url("/intro_completa_fondo.gif");
    background-size: cover;
  }

  #link {
    display: block;
    position: absolute;
    width: 100%;
    bottom: 0;
    top: 1300px;
    line-height: 0; 
    font-size: 0;
    color: transparent; 
  }

app/views/games/punishment_failure.html.slim
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.min.js"
css:
  body {
    margin: 0;
  }
javascript:

  var text;
  var game = new Phaser.Game("100", "100", Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

  function preload() {
    game.load.spritesheet('fruits', '/fruitnveg64wh37.png', 64, 37, 37);
    game.load.spritesheet('button', '/button_sprite_sheet.png', 193, 71);
  }

  var mummy;
  var anim;
  var loopText;
  var punish;
  var mercy;
  var text;
  var style;
  var currentQuestion;

  function create() {
    fruits = game.add.sprite(20, 100, 'fruits', 2);
    fruits.scale.set(4);
    fruits.smoothed = false;
    anim = fruits.animations.add('walk');
    anim.onLoop.add(animationLooped, this);
    style = { font: "bold 24px fedra", fill: "#fff", wordWrap: true, wordWrapWidth: 490 , align: "center"};
    text = game.add.text(30, 350, 'Fracaso', style);

    anim.play(10, true);
  }

  function animationLooped(sprite, animation) {
    if (animation.loopCount === 1)
    {
      animation.loop = false;
      nextAction();
    }
  }

  function nextAction() {
    window.location.href = "#{ cruz_player_game_path(@player, @game)}";
  }


  function update() {

  }

app/views/games/punishment_success.html.slim
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.min.js"
css:
  body {
    margin: 0;
  }
javascript:


  var text;
  var game = new Phaser.Game("100", "100", Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

  function preload() {
    game.load.spritesheet('shoot', '/shoot.png', 1040, 740, 12);
    game.load.spritesheet('button', '/button_sprite_sheet.png', 193, 71);
    game.load.spritesheet('mercyButton', '/mercy_sprite_sheet.png', 200, 70);

  }

  var anim;
  var loopText;
  var punish;
  var mercy;
  var text;
  var style;
  var currentQuestion;

  function create() {
    shoot = game.add.sprite(10, 10, 'shoot', 2);
    shoot.scale.set(1);
    shoot.smoothed = false;
    anim = shoot.animations.add('walk');
    anim.onComplete.add(function () { 
      style = { font: "bold 24px fedra", fill: "#fff", wordWrap: true, wordWrapWidth: 490 , align: "center"};
      window.location.href = "#{ player_game_path(@player, @game)}";
    }, this);
    anim.play(8, false);
  }

  function nextAction() {
  }


  function update() {

  }

app/views/games/show.html.slim
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.min.js"

css:
  body {
    margin: 0;
  }
javascript:

  var game = new Phaser.Game("100", "100", Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

  function preload() {
    game.load.spritesheet('mummy', '/metalslug_mummy37x45.png', 37, 45, 18);
    game.load.spritesheet('fruits', '/fruitnveg64wh37.png', 64, 37, 37);
    game.load.spritesheet('finishButton', '/finish_sprite_sheet.png', 200, 70);
    game.load.spritesheet('mercyButton', '/mercy_sprite_sheet.png', 200, 70);
    game.load.image('layout', '/fondo_preguntas.png', 520, 800);
    game.load.image('cunado', '/cunado_solo.png', 520, 800);
    game.load.image('botones', '/botones.png', 520, 800);
  }


  var anim;
  var loopText;
  var punish;
  var mercy;
  var text;
  var style;
  var currentQuestion;

  function create() {
    tilesprite = game.add.tileSprite(0, 0, 520, 800, 'layout');
    tilesprite.scale.set(2);
    speech = game.add.tileSprite(0, 100, 520, 800, 'botones');
    speech.scale.set(1.9);
    tilesprite = game.add.tileSprite(0, 55, 520, 800, 'cunado');
    tilesprite.scale.set(2);

    punish = game.add.button(85, 1340, 'finishButton', punishAction, this, 0, 1);
    mercy = game.add.button(545, 1340, 'mercyButton', mercyAction, this, 0, 1);

    mercy.scale.set(1.9);
    punish.scale.set(1.9);


    style = { font: "bold 48px fedra", fill: "#010101", wordWrap: true, wordWrapWidth: 800 , align: "center"};
    text = game.add.text(120, 900, '' , style);

    getQuestion(text)
  }

  function createQuestion (questionText) {
    text.setText(questionText);
  }

  function punishAction () {
    if(validateAnswer(false)) {
      window.location.href = "#{ punishment_success_player_game_path(@player, @game)}";
    } else {
      window.location.href = "#{ turra_player_game_path(@player, @game)}";
    }
  }

  function mercyAction () {
    if(validateAnswer(true)) {
      window.location.href = "#{ player_game_path(@player, @game)}";
    } else {
      window.location.href = "#{ mercy_failure_player_game_path(@player, @game)}";
    }
  }

  function animationLooped(sprite, animation) {
    if (animation.loopCount === 1)
    {
      loopText = game.add.text(32, 64, 'Animation looped', { fill: 'white' });
    }
  }


  function validateAnswer(optionSelected) {
    return(optionSelected === currentQuestion.truth);
  }

  function update() {

  }

  function getQuestion(text) {
    $.ajax({
      url: "#{new_player_game_question_path(@player, @game)}",
      success: function(response){
        currentQuestion = response;
        createQuestion(currentQuestion.description);
      },
      error: function(response){console.log("Adios", response)},
      dataType: "JSON"
    })
  }

app/views/games/turra.html.slim
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.min.js"
css:
  body {
    margin: 0;
  }
javascript:


  var text;
  var game = new Phaser.Game("100", "100", Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

  function preload() {
    game.load.image('final', '/final_has_perdido.png', 289, 187);
  }

  var anim;
  var loopText;
  var punish;
  var mercy;
  var text;
  var style;
  var currentQuestion;

  function create() {
  	tilesprite = game.add.tileSprite(0, 0, 289, 187, 'final');
    tilesprite.scale.set(3.5);
  }

  function update() {

  }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cunadismo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/site/success.html.slim
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.min.js"
css:
  body {
    margin: 0;
  }
javascript:

  var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

  function preload() {
    game.load.spritesheet('mummy', '/metalslug_mummy37x45.png', 37, 45, 18);
  }

  var mummy;
  var anim;
  var loopText;

  function create() {
    mummy = game.add.sprite(200, 360, 'mummy', 5);
    mummy.scale.set(4);
    mummy.smoothed = false;
    anim = mummy.animations.add('walk');

    anim.onStart.add(animationStarted, this);
    anim.onLoop.add(animationLooped, this);
    anim.onComplete.add(animationStopped, this);

    anim.play(10, true);

  }

  function animationStarted(sprite, animation) {

      game.add.text(32, 32, 'Animation started', { fill: 'white' });

  }

  function animationLooped(sprite, animation) {

      if (animation.loopCount === 1)
      {
          loopText = game.add.text(32, 64, 'Animation looped', { fill: 'white' });
      }
      else
      {
          loopText.text = 'Animation looped x2';
          animation.loop = false;
      }

  }

  function animationStopped(sprite, animation) {

      game.add.text(32, 64+32, 'Animation stopped', { fill: 'white' });

  }

  function update() {

  }